### ISSUE TITLE
跑evf-sam2报错“RuntimeError: No available kernel. Aborting execution.“

### ISSUE THREAD

**Issue by chflame163** [hustvl/EVF-SAM#17]
您好，感谢开源这么棒的作品。我按说明配置运行，跑evf-sam没有问题，跑evf-sam2报错如下：
```
(evf-sam) PS E:\evf-sam\EVF-SAM> python inference.py --version E:\ComfyUI_Models\models\efv-sam\evf-sam2 --precision='fp16' --vis_save_path "E:\evf-sam\output" --model_type sam2 --image_path "E:\evf-sam\test\zebra.jpg" --prompt "front right zebra"
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\backbones\hieradet.py:72: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  x = F.scaled_dot_product_attention(
E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py:255: UserWarning: Memory efficient kernel not used because: (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:607.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py:255: UserWarning: Memory Efficient attention has been runtime disabled. (Triggered internally at ..\aten\src\ATen/native/transformers/sdp_utils_cpp.h:495.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py:255: UserWarning: Flash attention kernel not used because: (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:609.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py:255: UserWarning: CuDNN attention kernel not used because: (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:611.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py:255: UserWarning: The CuDNN backend needs to be enabled by setting the enviornment variable`TORCH_CUDNN_SDPA_ENABLED=1` (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:410.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
Traceback (most recent call last):
  File "E:\evf-sam\EVF-SAM\inference.py", line 194, in <module>
    main(sys.argv[1:])
  File "E:\evf-sam\EVF-SAM\inference.py", line 173, in main
    pred_mask = model.inference(
                ^^^^^^^^^^^^^^^^
  File "E:\evf-sam\EVF-SAM\model\evf_sam2.py", line 320, in inference
    low_res_masks, iou_predictions, _, _ = self.visual_model.sam_mask_decoder(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\mask_decoder.py", line 136, in forward
    masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks(
                                                            ^^^^^^^^^^^^^^^^^^^
  File "E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\mask_decoder.py", line 213, in predict_masks
    hs, src = self.transformer(src, pos_src, tokens)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py", line 101, in forward
    queries, keys = layer(
                    ^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py", line 167, in forward
    queries = self.self_attn(q=queries, k=queries, v=queries)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cc\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\evf-sam\EVF-SAM\model\segment_anything_2\sam2\modeling\sam\transformer.py", line 255, in forward
    out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: No available kernel. Aborting execution.

```
请指导如何解决？谢谢！

**Comment by CoderZhangYx** [comment]
check your pytorch version. pytorch>=2.0 is needed

**Comment by chflame163** [comment]
> check your pytorch version. pytorch>=2.0 is needed

I checked torch version, it is 2.3.1+cu121
```
(evf-sam) PS E:\evf-sam\EVF-SAM> pip show torch
Name: torch
Version: 2.3.1+cu121
```

**Comment by CoderZhangYx** [comment]
what is your gpu type and what is the cuda driver version of your gpu? please make sure that your cuda toolkit version is available under your cuda driver version.

**Comment by chflame163** [comment]
Sure, GPU is RTX 3070 16G，CUDA is 12.2,  It works very well with StableDiffusion.
<img width="656" alt="微信图片_20240827171420" src="https://github.com/user-attachments/assets/77223351-5037-4771-b75d-294d8a61e751">

**Comment by CoderZhangYx** [comment]
Could this issue help? https://github.com/facebookresearch/segment-anything-2/issues/48

**Comment by chflame163** [comment]
> It looks like this error originates from sam-2. Could this issue help? [facebookresearch/segment-anything-2#48](https://github.com/facebookresearch/segment-anything-2/issues/48)

Thanks. It worked.

**Comment by CoderZhangYx** [comment]
Glad it works.
